#WARNING: This file is automatically overwritten every time you close a project. 
#         Add any startup commands to maestro.cmd
#         ** Do NOT edit this file! **
projectprefer feedbackproperty="Title"
projectprefer feedbackproperties="s_m_title s_pdb_PDB_ID"
projectprefer phasefeedbackproperties=""
projectprefer show2dstructures=false
projectprefer 2dstructureheight=200
projectprefer 2dstructurewidth=300
entryexport selected_properties=""
entryexportspreadsheet selected_properties="glide emodel,glide gscore,MMGBSA dG Bind,Title,MMGBSA dG Bind Lipo,MMGBSA dG Bind Hbond,MMGBSA dG Bind Covalent,MMGBSA dG Bind Coulomb,MMGBSA dG Bind Packing,MMGBSA dG Bind SelfCont,MMGBSA dG Bind Solv GB,MMGBSA dG Bind vdW,MMGBSA dG Bind(NS),MMGBSA dG Bind(NS) Coulomb,MMGBSA dG Bind(NS) Covalent,MMGBSA dG Bind(NS) Hbond,MMGBSA dG Bind(NS) Lipo,MMGBSA dG Bind(NS) Packing,MMGBSA dG Bind(NS) SelfCont,MMGBSA dG Bind(NS) Solv GB,MMGBSA dG Bind(NS) vdW,MMGBSA moved residues,Entry Name"
projectprefer entrylistvisiblesubset=""
projectprefer entrylistcolumnwidths=""
projectprefer showentrylist2dstructures=false
projectprefer entrylist2dstructureheight=75
projectprefer entrylist2dstructurewidth=75
projectprefer showentryliststars=false
projectprefer enotationproperties=""
projectprefer muterowcolumncolors=false
